// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	APIKeyHeaderScopes = "APIKeyHeader.Scopes"
)

// BoxOfficeRecord defines model for BoxOfficeRecord.
type BoxOfficeRecord struct {
	// Budget The estimated production budget of the movie in USD.
	Budget *int64 `json:"budget,omitempty"`

	// Distributor The company that distributed the movie.
	Distributor *string `json:"distributor,omitempty"`

	// MpaRating The MPA (Motion Picture Association) rating.
	MpaRating *string `json:"mpaRating,omitempty"`

	// ReleaseDate The original theatrical release date in North America.
	ReleaseDate *openapi_types.Date `json:"releaseDate,omitempty"`
	Revenue     *struct {
		// OpeningWeekendUSA The opening weekend gross revenue in the USA in USD.
		OpeningWeekendUSA *int64 `json:"openingWeekendUSA,omitempty"`

		// Worldwide The total worldwide gross revenue in USD.
		Worldwide *int64 `json:"worldwide,omitempty"`
	} `json:"revenue,omitempty"`

	// Title The official title of the movie.
	Title *string `json:"title,omitempty"`
}

// CliError defines model for CliError.
type CliError struct {
	// CliError A short description of the error type.
	CliError *string `json:"error,omitempty"`

	// Message A detailed message explaining the error.
	Message *string `json:"message,omitempty"`
}

// GetMovieBoxOfficeParams defines parameters for GetMovieBoxOffice.
type GetMovieBoxOfficeParams struct {
	// Title The title of the movie to look up.
	Title string `form:"title" json:"title"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetMovieBoxOffice request
	GetMovieBoxOffice(ctx context.Context, params *GetMovieBoxOfficeParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetMovieBoxOffice(ctx context.Context, params *GetMovieBoxOfficeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMovieBoxOfficeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetMovieBoxOfficeRequest generates requests for GetMovieBoxOffice
func NewGetMovieBoxOfficeRequest(server string, params *GetMovieBoxOfficeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/boxoffice")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "title", runtime.ParamLocationQuery, params.Title); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetMovieBoxOfficeWithResponse request
	GetMovieBoxOfficeWithResponse(ctx context.Context, params *GetMovieBoxOfficeParams, reqEditors ...RequestEditorFn) (*GetMovieBoxOfficeResponse, error)
}

type GetMovieBoxOfficeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BoxOfficeRecord
	JSON400      *CliError
	JSON401      *CliError
	JSON404      *CliError
	JSON500      *CliError
}

// Status returns HTTPResponse.Status
func (r GetMovieBoxOfficeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMovieBoxOfficeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetMovieBoxOfficeWithResponse request returning *GetMovieBoxOfficeResponse
func (c *ClientWithResponses) GetMovieBoxOfficeWithResponse(ctx context.Context, params *GetMovieBoxOfficeParams, reqEditors ...RequestEditorFn) (*GetMovieBoxOfficeResponse, error) {
	rsp, err := c.GetMovieBoxOffice(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMovieBoxOfficeResponse(rsp)
}

// ParseGetMovieBoxOfficeResponse parses an HTTP response from a GetMovieBoxOfficeWithResponse call
func ParseGetMovieBoxOfficeResponse(rsp *http.Response) (*GetMovieBoxOfficeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMovieBoxOfficeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BoxOfficeRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CliError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest CliError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CliError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest CliError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
