services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3



  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: movie_db
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3